### ISSUE TITLE
A few fusions in Seracare reference materials not detected 

### ISSUE THREAD

**Issue by foxchase** [Zheng-NGS-Lab/SplitFusion#3]
Hello,
I tried with splitfusion (hg19) with Seracare RMs (FFPE V4 and Myeloid RNA fusion):
https://seracare.com/Seraseq-FFPE-Fusion-RNA-RM-v4-0710-0496/ 
https://seracare.com/Seraseq-Myeloid-Fusion-RNA-Mix-0710-0407/
There are a few fusions not detected by SplitFusion; especially in the myeloid RM, not found in the no-filter file.
If you like the fastq files to try I can send them to you.

Thank you and best wishes.

**Comment by WeiweiBian** [comment]
Hi,

Thanks for your interests in SplitFusion.

You can share the code you used and try with our latest release. Otherwise you can upload you fastq files here or send to my email, weiwei.bian@ki.se.

Best,
Weiwei

**Comment by WeiweiBian** [comment]
Hi,

Thanks for your interests in SplitFusion.

You can share the code you used and try with our latest release. Please send your fastq files to us, like sharing a dropbox or goole drive link. Thanks.

Best,
Weiwei
